<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="adlordy.Assignment.IntegrationTests.dll" environment="64-bit .NET (unknown version) [collection-per-class, parallel (8 threads)]" test-framework="xUnit.net 2.2.0.3444" run-date="2016-12-24" run-time="12:13:20" total="17" passed="3" failed="14" skipped="0" time="13.391" errors="0">
    <errors />
    <collection total="4" passed="1" failed="3" skipped="0" name="Test collection for adlordy.Assignment.IntegrationTests.HttpClientTests" time="3.142">
      <test name="adlordy.Assignment.IntegrationTests.HttpClientTests.TestEmpty_WhenLeftOrRightNotSet(id: \&quot;2\&quot;, left: [0], right: null)" type="adlordy.Assignment.IntegrationTests.HttpClientTests" method="TestEmpty_WhenLeftOrRightNotSet" time="1.1254968" result="Fail">
        <failure exception-type="System.Net.Http.HttpRequestException">
          <message><![CDATA[System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.HttpClientTests.<TestEmpty_WhenLeftOrRightNotSet>d__3.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\HttpClientTests.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.HttpClientTests.TestEmpty_WhenLeftOrRightNotSet(id: \&quot;3\&quot;, left: null, right: [0])" type="adlordy.Assignment.IntegrationTests.HttpClientTests" method="TestEmpty_WhenLeftOrRightNotSet" time="1.002617" result="Fail">
        <failure exception-type="System.Net.Http.HttpRequestException">
          <message><![CDATA[System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.HttpClientTests.<TestEmpty_WhenLeftOrRightNotSet>d__3.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\HttpClientTests.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.HttpClientTests.TestEmpty_WhenNeitherLeftNorRightSet" type="adlordy.Assignment.IntegrationTests.HttpClientTests" method="TestEmpty_WhenNeitherLeftNorRightSet" time="1.0067466" result="Fail">
        <failure exception-type="System.Net.Http.HttpRequestException">
          <message><![CDATA[System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<GetAsync>d__5.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.HttpClientTests.<TestEmpty_WhenNeitherLeftNorRightSet>d__2.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\HttpClientTests.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.HttpClientTests.TestBadRequest_WhenDataIsNull" type="adlordy.Assignment.IntegrationTests.HttpClientTests" method="TestBadRequest_WhenDataIsNull" time="0.0073754" result="Pass" />
    </collection>
    <collection total="13" passed="2" failed="11" skipped="0" name="Test collection for adlordy.Assignment.IntegrationTests.DiffServiceTest" time="13.175">
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEmpty" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestEmpty" time="1.1258218" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEmpty() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 30
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestNull(left: null, right: [])" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestNull" time="1.0069121" result="Pass" />
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestNull(left: [], right: null)" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestNull" time="1.0034512" result="Pass" />
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMiddleSingle" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestMiddleSingle" time="1.0030203" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMiddleSingle() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 76
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMiddleMultiple" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestMiddleMultiple" time="1.0035521" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMiddleMultiple() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 89
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestBeginningSingle" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestBeginningSingle" time="1.0035461" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestBeginningSingle() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 50
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestSizeDoNotMatch(left: [1, 1, 1, 1, 1], right: [])" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestSizeDoNotMatch" time="1.0043031" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestSizeDoNotMatch(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 40
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestSizeDoNotMatch(left: [], right: [1, 1, 1, 1, 1])" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestSizeDoNotMatch" time="1.0037617" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestSizeDoNotMatch(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 40
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestWhole" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestWhole" time="1.0039899" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestWhole() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 143
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestBeginningMultiple" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestBeginningMultiple" time="1.0035119" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestBeginningMultiple() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 63
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMany" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestMany" time="1.0042884" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestMany() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 128
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEndSingle" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestEndSingle" time="1.0039166" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEndSingle() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 102
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
      <test name="adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEndMultiple" type="adlordy.Assignment.IntegrationTests.DiffServiceTest" method="TestEndMultiple" time="1.0047707" result="Fail">
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)\r\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n-------- System.Net.Http.WinHttpException : A connection with the server could not be established]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.GetDiff(Byte[] left, Byte[] right) in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 22
   at adlordy.Assignment.IntegrationTests.DiffServiceTest.TestEndMultiple() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffServiceTest.cs:line 115
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.JsonExtensions.<PutAsJsonAsync>d__1`1.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\JsonExtensions.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at adlordy.Assignment.IntegrationTests.DiffClient.<PutAsync>d__8.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\DiffClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at adlordy.Assignment.IntegrationTests.RemoteDiffService.<>c__DisplayClass3_0.<<GetDiff>b__0>d.MoveNext() in C:\Work\adlordy.Assignment\test\adlordy.Assignment.IntegrationTests\RemoteDiffService.cs:line 24
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()]]></stack-trace>
        </failure>
      </test>
    </collection>
  </assembly>
</assemblies>